### ISSUE TITLE
Make a bulleted list.

### ISSUE THREAD

**Issue by trainzman54** [SullivanNorthHS/012.A-Cheatsheets#29]
The lists need to be either bulleted or numbered when explaining how to do something. @jacksack20 @amillie. For a bulleted list, put an asterisk {*} and a space before each element of a list. For numbers, you just put the number and a period {.} immediately after the number with a space between the period and the first letter of the line.

**Comment by jacksack20** [comment]
Thanks Howie.

**Comment by jacksack20** [comment]
.
